version: '3'

services:
  vault:
    image: vault
    command: server -config=/vault/config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
    volumes:
      - "vault-data:/vault/file"
      - "./vault/vault_config.json:/vault/config.json"

  consul:
    image: consul
    command: agent -server -config-dir=/consul/config
    volumes:
      - "./consul:/consul/config"
      - "consul-data:/consul/data"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"

  app:
    build: app/.
    command: sh /vault-init.sh
    environment:
      - VAULT_ADDR=http://vault:8200
    # This is pretty hacky to help deal with getting the vault token
    volumes:
      - "apphome:/root"
    depends_on:
      - vault

volumes:
  apphome:
  vault-data:
  consul-data:
