version: '3'

services:

  vault:
    image: vault
    command: server
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_LOCAL_CONFIG={"backend":{"file":{"path":"/vault/file"}},"default_lease_ttl":"168h","max_lease_ttl":"720h","listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":1}}}
    expose:
      - 8200

  app:
    build: . 
    command: sh /app-init.sh
    environment:
      - VAULT_ADDR=http://vault:8200
    ports:
      - "8080:8080"
    volumes:
      - "apphome:/root"
    depends_on:
      - vault

volumes:
  apphome:
